# Check GitHub Actions documentation at:
# https://github.com/marketplace/actions/pypi-publish
name: 👨‍🔬 PyPI Test Publishing

on:
  push:
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+-*'
      - 'v?[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: 🐍 Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: 💽 Install Invoke
      run: pip install invoke

    - name: 💽 Install poetry
      run: invoke poetry-download

    - name: 📦 Build
      run: invoke build

    - name: 🗃️ Upload Builds
      uses: actions/upload-artifact@v4
      with:
        name: test-package-distribution
        path: dist/
        overwrite: true
        retention-days: 30

  deploy-test:
    name: Upload to Test PyPI
    runs-on: ubuntu-latest
    needs: build
    environment:
      # TODO Create the "development" environment in https://github.com/galactipy/python-project-gh-workflow/settings/environments/new
      name: development
      url: https://test.pypi.org/p/python-project-gh-workflow

    steps:
    - name: 🗃️ Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: test-package-distribution
        path: dist/

    - name: 📤 Deploy to PyPI test environment
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        # TODO Set the TESTPYPI_TOKEN variable for https://test.pypi.org in the development environment
        password: ${{ secrets.TESTPYPI_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
        attestations: false
