# Check GitHub Actions documentation at:
# https://github.com/marketplace/actions/pypi-publish
name: 🔖 Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      publish:
        description: Allow publishing to PyPI in production
        required: true
        type: boolean

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    if: ${{ inputs.publish }}
    steps:
    - uses: actions/checkout@v4

    - name: 🐍 Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: 💽 Install Invoke
      run: pip install invoke

    - name: 💽 Install poetry
      run: invoke poetry-download

    - name: 📦 Build
      run: invoke build

    - name: 🗃️ Upload Builds
      uses: actions/upload-artifact@v4
      with:
        name: prod-package-distribution
        path: dist/
        overwrite: true
        retention-days: 30

  deploy-prod:
    name: Upload Release to PyPI
    runs-on: ubuntu-latest
    needs: build
    if: ${{ inputs.publish && github.ref_type == 'tag' }}
    environment:
      # TODO Create the "production" environment in https://github.com/galactipy/python-project-gh-workflow/settings/environments/new
      name: production
      url: https://pypi.org/p/python-project-gh-workflow
    permissions:
      # TODO Set up trusted publishing (https://docs.pypi.org/trusted-publishers/)
      id-token: write

    steps:
    - name: 🗃️ Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: prod-package-distribution
        path: dist/

    - name: 📤 Deploy to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
